/*
 * Copyright (C) 2022 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
//trace采集开始
export const catch_trace_start = 1
//trace采集结束
export const catch_trace_finish = 2
//trace采集第一次运行中
export const catch_trace_first_running = 3
//trace采集运行中
export const catch_trace_running = 4
//trace 采集 停止后间隔60次
export const catch_trace_times = 60
//悬浮框标记
export const CURRENTNOW=0
export const SHELLBACKTEMP=1
export const DDRFREQUENCY=2
export const GPUFREQUENCY=3
export const CPU0FREQUENCY=4
export const CPU1FREQUENCY=5
export const CPU2FREQUENCY=6
export const RAM=7
export const FPS=8
